language: node_js
node_js:
  - "node"
script: npm run lint:lib:ci && npm run build:lib
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
cache:
  directories:
    - "node_modules"
